BUNDLES = [
    "//apps/evpn-route-service/api:onos-apps-evpn-route-service-api",
    "//apps/evpn-route-service/app:onos-apps-evpn-route-service-app",
    "//apps/routing-api:onos-apps-routing-api",
    "//apps/routing/common:onos-apps-routing-common",
]

onos_app(
    category = "Traffic Engineering",
    included_bundles = BUNDLES,
    title = "EVPN Routing",
    required_apps = [
        "org.onosproject.route-service",
    ],
    url = "http://onosproject.org",
)
